### ISSUE TITLE
[Tablet] cant see text because of background image

### ISSUE THREAD

**Issue by oksanarutska** [IgnatSemchuk/dsng#4] opened 2018-11-13 21:43 UTC
![image](https://user-images.githubusercontent.com/42785757/48444871-dc7f1d80-e79d-11e8-8ac0-13e5a1fee3f2.png)

**Comment by IgnatSemchuk** [comment] 2018-11-16 16:00
done
Duplicate of #12

**Closed as completed** 2018-11-18 20:11 UTC
Labels: done
